//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK_Assistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JK_Assistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LanguageGeneration {
            get {
                object obj = ResourceManager.GetObject("LanguageGeneration", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;type&quot;: &quot;AdaptiveCard&quot;,
        ///    &quot;$schema&quot;: &quot;http://adaptivecards.io/schemas/adaptive-card.json&quot;,
        ///    &quot;version&quot;: &quot;1.3&quot;,
        ///    &quot;body&quot;: [
        ///        {
        ///            &quot;type&quot;: &quot;ColumnSet&quot;,
        ///            &quot;columns&quot;: [
        ///                {
        ///                    &quot;type&quot;: &quot;Column&quot;,
        ///                    &quot;width&quot;: &quot;stretch&quot;,
        ///                    &quot;items&quot;: [
        ///                        {
        ///                            &quot;type&quot;: &quot;TextBlock&quot;,
        ///                            &quot;text&quot;: &quot;&quot;,
        ///                            &quot;wrap&quot;: true,
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoteAdaptiveCard {
            get {
                return ResourceManager.GetString("NoteAdaptiveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;type&quot;: &quot;AdaptiveCard&quot;,
        ///    &quot;$schema&quot;: &quot;http://adaptivecards.io/schemas/adaptive-card.json&quot;,
        ///    &quot;version&quot;: &quot;1.2&quot;,
        ///    &quot;body&quot;: [
        ///        {
        ///            &quot;type&quot;: &quot;ActionSet&quot;,
        ///            &quot;actions&quot;: [
        ///                {
        ///                    &quot;type&quot;: &quot;Action.OpenUrl&quot;,
        ///                    &quot;title&quot;: &quot;Open Search Results&quot;,
        ///                    &quot;url&quot;: &quot;google.com&quot;
        ///                }
        ///            ]
        ///        }
        ///    ]
        ///}.
        /// </summary>
        internal static string SearchResultCard {
            get {
                return ResourceManager.GetString("SearchResultCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;$schema&quot;: &quot;http://adaptivecards.io/schemas/adaptive-card.json&quot;,
        ///    &quot;type&quot;: &quot;AdaptiveCard&quot;,
        ///    &quot;version&quot;: &quot;1.2&quot;,
        ///    &quot;body&quot;: [
        ///        {
        ///            &quot;type&quot;: &quot;TextBlock&quot;,
        ///            &quot;size&quot;: &quot;Medium&quot;,
        ///            &quot;weight&quot;: &quot;Bolder&quot;,
        ///            &quot;text&quot;: &quot;GOOGLE&quot;,
        ///            &quot;horizontalAlignment&quot;: &quot;Center&quot;,
        ///            &quot;wrap&quot;: true
        ///        },
        ///        {
        ///            &quot;type&quot;: &quot;Input.Text&quot;,
        ///            &quot;style&quot;: &quot;text&quot;,
        ///            &quot;id&quot;: &quot;SearchValue&quot;,
        ///            &quot;placeholder&quot;: &quot;Enter valu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WebSearchCard {
            get {
                return ResourceManager.GetString("WebSearchCard", resourceCulture);
            }
        }
    }
}
